import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg"></div>
      <style jsx>{`
        .bg {
          width: 50vw;
          height: 100vh;
          margin: 0;
          background-image: url('/logoBg.svg');
          background-repeat: repeat;
          background-position: right;
          background
          background-size: 59px;
        }
      `}</style>
    </div>
  )
}
